# Copyright Â© 2025 Leviftas authors. All rights reserved.
#
# Licensed under the GNU General Public License v3.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.gnu.org/licenses/gpl-3.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# config.yml
#
# Issue template configuration for Leviftas project.
#
# - Author   : FrostLeo <frostleo.dev@gmail.com>
# - Created  : 2025/10/15
# - Modified : 2025/10/15

blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/Frost-Leo/Leviftas/discussions
    about: Ask questions and discuss with the community
  - name: ðŸ“– Documentation
    url: https://github.com/Frost-Leo/Leviftas/wiki
    about: Check our documentation and guides
  - name: ðŸ”’ Security Issues
    url: https://github.com/Frost-Leo/Leviftas/security/advisories/new
    about: Report security vulnerabilities privately